### ISSUE TITLE
CSS3实现图片变黑白

### ISSUE THREAD

**Issue by wuxianqiang** [wuxianqiang/project#9]
```css
img.desaturate {
            -webkit-filter: grayscale(100%);
            -moz-filter: grayscale(100%);
            -ms-filter: grayscale(100%);
            -o-filter: grayscale(100%);
            filter: grayscale(100%);
    }
```
